name: expesne_tracker_app
description: expesne_tracker_app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.2.0"

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.2.0
  equatable: ^2.0.5
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.3.0
  get_it: ^7.2.0
  google_sign_in: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  shimmer: ^2.0.0
  sign_in_with_apple: ^6.1.1
  svg_flutter: ^0.0.1
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
